# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: Swift ${{ matrix.swift }} on macos
    strategy:
      matrix:
        swift: [ "5.8", "5.9" ]
        
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
          
      - name: Build
        run: swift build

      - name: Run tests
        run: swift test --enable-code-coverage

  test-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Swift
      run: |
        wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        wget https://swift.org/builds/swift-5.5.3-release/ubuntu2004/swift-5.5.3-RELEASE/swift-5.5.3-RELEASE-ubuntu20.04.tar.gz
        tar xzf swift-5.5.3-RELEASE-ubuntu20.04.tar.gz --directory /tmp --strip-components=1
        export PATH="/tmp/usr/bin:$PATH"

    - name: Build and Run Ubuntu Tests
      run: swift test --enable-code-coverage

        
